# top level stuff you probably don't need to touch
title: dieresonanz
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
plugins: 
 - jekyll-paginate
 - jekyll-sitemap
port: 3000
safe: true
local_backend: true

# needed for travis-ci build
exclude: [vendor]

collections:
  reviews:
    output: false
    sort_by: year
  content:
    output: false  # or true if you want Jekyll to render individual pages